# -*- coding: utf-8 -*-
import sys

print "帰る？"
print "帰る？"
print "帰る？"
print "帰る？"
print "帰る？"
print "帰る？"
print "帰る？"
print "帰る？"
print "帰る？"
print "帰る？"
print "帰る？"
print "帰る？"
print "帰る？"
print "帰る？"
print "帰る？"
print "帰る？"
print "帰る？"
print "帰る？"
print "帰る？"
print "帰る？"
print "帰る？"
print "帰る？"
print "帰る？"
print "帰る？"
print "帰る？"
print "おおおおお！"
print "ouchi kaeru!!"
print "ouchi kaeru!!"
print "ouchi kaeru!!"
print "ouchi kaeru!!"
print "ouchi kaeru!!"
print "ouchi kaeru!!"
print "ouchi kaeru!!"
print "ouchi kaeru!!"
print "ouchi kaeru!!"
print "ouchi kaeru!!"
print "ouchi kaeru!!"
print "ouchi kaeru!!"
print "ouchi kaeru!!"
print "ouchi kaeru!!"
print "ouchi kaeru!!"
print "ouchi kaeru!!"
print "ouchi kaeru!!"
print "ouchi kaeru!!"
print "ouchi kaeru!!"
print "ouchi kaeru!!"
print "ouchi kaeru!!"
print "ouchi kaeru!!"
print "ouchi kaeru!!"
print "ouchi kaeru!!"
print "ouchi kaeru!!"
print "ouchi kaeru!!"
print "ouchi kaeru!!"
print "ouchi kaeru!!"
print "ouchi kaeru!!"
print "ouchi kaeru!!"
print "ouchi kaeru!!"
print "ouchi kaeru!!"
print "ouchi kaeru!!"
print "ouchi kaeru!!"
print "ouchi kaeru!!"
print "ouchi kaeru!!"
print "ouchi kaeru!!"
print "ouchi kaeru!!"
print "ouchi kaeru!!"
print "ouchi kaeru!!"
print "ouchi kaeru!!"
print "ouchi kaeru!!"
print "ouchi kaeru!!"
print "ouchi kaeru!!"
print "ouchi kaeru!!"
print "ouchi kaeru!!"
print "ouchi kaeru!!"
print "ouchi kaeru!!"

